### ISSUE TITLE
set Layout params

### ISSUE THREAD

**Issue by faizandedia** [dm77/ZBarScanner#1]
Hello, 

How can I change the size of the camera preview? I don't want to cover it full screen, how can i define frame to camera preview instead of whole screen?

Thanks

**Comment by dm77** [comment]
Sorry for not having replied sooner. Were you able to find a solution? If not, you can perhaps play with the method getOptiomalPreviewSize() in CameraPreview.java to get your desired size. If you are looking to add a rectangular frame around the camera preview, you can find some hints from the ZXing android app (http://code.google.com/p/zxing/source/browse/trunk/android/src/com/google/zxing/client/android/camera/CameraManager.java)
