### ISSUE TITLE
Code39

### ISSUE THREAD

**Issue by albertsmus** [dm77/ZBarScanner#11]
When i use a printed barcode label with Code39 or Code93 or even Code128 in "data.getStringExtra(ZBarConstants.SCAN_RESULT)" part of code i get the string "BARCODEID" instead of the barcode number i take it when i use UPCA in my printed labels. Why is that?
Thanks for help

**Comment by dm77** [comment]
Unfortunately this is an SDK issue :(. Please check with http://sourceforge.net/projects/zbar/files/AndroidSDK/
