### ISSUE TITLE
Inaccurate ISBN Numbers from scan

### ISSUE THREAD

**Issue by AlainArduain** [dm77/ZBarScanner#13]
I am getting an error when I read the ISBNs on the back of books.  A majority of the time the ISBN is inaccurate.  I am wondering if this has something to do with the scan modes I am using? I had to use EAN13 and 8 to get it to read.  Any help would be appreciated.  

On another note the scan result type always returns null, why is that?

Edit: Also when using ISBN it won't actually read the bar codes on the back of books.

Thank you.

**Comment by Chintamani17** [comment]
I am facing exactly the same issue. Please need some help.

**Comment by dm77** [comment]
Unfortunately this is outside the scope of the project. You probably want to take this up with: http://sourceforge.net/projects/zbar/files/AndroidSDK/
