### ISSUE TITLE
Not able to scan barcode in some of the latest devices launched by google mainly Motorola Moto X

### ISSUE THREAD

**Issue by varun2264** [dm77/ZBarScanner#14]
Don't know but due to some reason the success variable for success in the onAutoFocus(boolean success, Camera camera) always returns false in this device whereas it works just fine on rest of the devices.

How m i supposed to fix this issue, a day or two have already gone in vain.

**Comment by varun2264** [comment]
is it something related to the aspect ratio, because for Motorola Moto X the aspect ratio comes out to be of 0.5 as its a 720 X 1280 device.

**Comment by dm77** [comment]
Thank you for the bug report. I will no longer be maintaining this project. I will be spending my time on https://github.com/dm77/barcodescanner
