### ISSUE TITLE
Getting garbage value.

### ISSUE THREAD

**Issue by Chintamani17** [dm77/ZBarScanner#15]
Hi,
    I am using ZBar library for scanning multiple barcode. When I am trying to scan same barcode for multiple times, everytime It return different values. First time it returns correct value. I am trying to scan a barcode of type  EAN13, UPCA, UPCE and EAN8.
I am using the attached image.
Please help to resolve this.

Thanks in Advacnce.
![samplebarcode](https://f.cloud.github.com/assets/1064527/1209471/66db0898-25ea-11e3-984f-0b44c5923f8a.png)

**Comment by dm77** [comment]
Make sure you are using the right scan codes. But if the issue further persists, please contact: http://sourceforge.net/projects/zbar/files/AndroidSDK/
