### ISSUE TITLE
Android Studio & ZBar

### ISSUE THREAD

**Issue by jodynek** [dm77/ZBarScanner#18]
Hello,
had someone luck with integration ZBar into Android Studio project ? After setting gradle and successfull compilation of my project, ZBar crashing on following:

```
  Intent intent = new Intent(this, ZBarScannerActivity.class);
  startActivityForResult(intent, ZBAR_SCANNER_REQUEST);
```

Thanks for any help.

Regards, Petr

**Comment by JpCapdevila** [comment]
Hello, I did had luck!

My app was crashing in those lines.

The issue was that "this", should be replaced for the context where you are
calling. In my case i replaced "this" for "MyActivity.this".

Hope that helps you somehow.

2013/10/15 jodynek notifications@github.com

**Comment by jodynek** [comment]
Unfortunately, that's not my case... Still crashing...

I made simple test project - can you please look at them, if there is not something different wrong (gradle...) ?
http://sdrv.ms/194UpMU

Thanks a lot for your help...

**Comment by JpCapdevila** [comment]
Sure, I'll take a look later and also compare with my code. (I'm not at
home right now).

2013/10/15 jodynek notifications@github.com

**Comment by jodynek** [comment]
Thanks a lot for your time, that's help me very much...

**Comment by dcu** [comment]
can you guys post your build.gradle file? I am not sure how to integrate this project.

**Comment by jodynek** [comment]
Hi,
yes, here is...

Best regards, Petr

2013/11/24 David Cuadrado notifications@github.com

**Comment by dcu** [comment]
looks like you forgot to paste it or github filtered it out

**Comment by jodynek** [comment]
Ok, so what now ?

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.5.+'
    }
}
apply plugin: 'android'

repositories {
    mavenCentral()
}

android {
    compileSdkVersion 18
    buildToolsVersion "17.0.0"

```
defaultConfig {
    minSdkVersion 8
    targetSdkVersion 18
}
```

}

dependencies {
compile 'com.android.support:appcompat-v7:18.0.0'
    compile files('libs/android-support-v4.jar')
    compile files('libs/zbar.jar')
}

task copyNativeLibs(type: Copy) {
    from(new File('libs')) { include '**' }
    into new File(buildDir, 'native-libs')
}

tasks.withType(Compile) { compileTask -> compileTask.dependsOn
copyNativeLibs }

clean.dependsOn 'cleanCopyNativeLibs'

tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask
->
    pkgTask.jniDir new File(buildDir, 'native-libs')
}

2013/11/24 David Cuadrado notifications@github.com

**Comment by dcu** [comment]
ok thank you
