### ISSUE TITLE
Zbar scanner Read non barcodes.

### ISSUE THREAD

**Issue by pramodpnckr** [dm77/ZBarScanner#22]
My application with zbar scanner read some values from wall. your sample application also read some values from the wall.My testing device is Samsung galaxy s4 and Samsung galaxy S3. 

![screenshot_2013-11-27-18-00-08 1](https://f.cloud.github.com/assets/5967470/1631245/fb94c9dc-575f-11e3-8501-2963dd35e325.png)

**Comment by dm77** [comment]
Unfortunately this is outside the scope of this project. This is probably an SDK issue and you might want to communicate with them: http://sourceforge.net/projects/zbar/files/AndroidSDK/
