### ISSUE TITLE
Zbar scanner Read non barcodes.

### ISSUE THREAD

**Issue by pramodpnckr** [dm77/ZBarScanner#23]
My android application with Zbar read some values from the wall. Your example code also behave like this. My testing device is Samsung galaxy S4 and S3.
![screenshot_2013-11-27-18-00-08 1](https://f.cloud.github.com/assets/5967470/1631292/1de6cb38-5761-11e3-9f90-ebf6867a6699.png)

**Comment by dm77** [comment]
Unfortunately this is an SDK issue: http://sourceforge.net/projects/zbar/files/AndroidSDK/

**Comment by pramodpnckr** [comment]
@DushyanthMaguluru How can I fix the issue?
