### ISSUE TITLE
scanCrop method not available in Android as IOS

### ISSUE THREAD

**Issue by kuraneabhijit** [dm77/ZBarScanner#24]
Hi, It was great working with ZBarScanner code. Great work Dushyanth.
But now I'm facing one issue. I'm unable to set area to scan as in IOS.
I checked stackoverflow for solution but no any results found.
I got below link,
http://stackoverflow.com/questions/18918211/how-to-change-area-of-scan-zbar
Please reply.

**Comment by dm77** [comment]
Thank you for reporting the issue. I believe the iOS zbar library is an official project, while what I did is an extension to the original library: http://sourceforge.net/projects/zbar/files/AndroidSDK/

Though there are lot of improvements in the pipe-line like fragment support, flash support, better UI etc. I am not sure I can promise adding this particular feature.
