### ISSUE TITLE
Camera not filling the entire screen

### ISSUE THREAD

**Issue by teng-dtit** [dm77/ZBarScanner#26]
I wanted my camera to be in portrait mode so i followed this -> https://github.com/DushyanthMaguluru/ZBarScanner/commit/ab644e2342d9e0b52d5ae1eb6e4d774497f1094f

The camera is now in portrait mode but the problem is that the camera is not filling the entire screen, the height is filled but the width is not, there are white borders on the left and right area.

**Comment by dm77** [comment]
Sorry for the delayed response. I will try to fix this before the weekend.
