### ISSUE TITLE
Work with fragment

### ISSUE THREAD

**Issue by Maculotti** [dm77/ZBarScanner#27]
How can implement the method onActivityResult in a Fragment?

Eclipse show me an error on RESULT_OK on if statement.
I have this problem only with fragment. Infact I use this in MainActivity and it's good.

**Comment by dm77** [comment]
Your issue could be related to http://stackoverflow.com/questions/6147884/onactivityresult-not-being-called-in-fragment

**Comment by Maculotti** [comment]
thanks
