### ISSUE TITLE
When using a Nexus 5 Scanning causes a fatal error.

### ISSUE THREAD

**Issue by varun2264** [dm77/ZBarScanner#28]
Hello Dushyanth ,
When ever i press my Scan button and try to scan in my Nexus 5 version 4.2.2, the phone freezes following which i need to hard shutdown in-order to access my device.

Works okay on the Nexus 4, with the same Android 4.4.2 os.The scan function worked before.
Please help me with this Dushyanth, it been really bugging me alot.

Thanks,
Varun Thakur.

**Comment by dm77** [comment]
I am looking at this now.

**Comment by dm77** [comment]
Hi @varun2264 , I haven't been able to duplicate this on my nexus 5. Can you try commenting the method
protected void onLayout(boolean changed, int l, int t, int r, int b)  in CameraPreview.java and see if that fixes your issue? Thanks.

**Comment by dm77** [comment]
Thank you for the bug report. I will no longer be maintaining this project. I will be spending my time on https://github.com/dm77/barcodescanner
