### ISSUE TITLE
loadLibrary problem

### ISSUE THREAD

**Issue by YakovAvramenko** [dm77/ZBarScanner#29]
I have got. Not sure about kind of device

Stack Trace

---

0   java.lang.ExceptionInInitializerError
1       at java.lang.Class.newInstanceImpl(Native Method)
2       at java.lang.Class.newInstance(Class.java:1319)
3       at android.app.Instrumentation.newActivity(Instrumentation.java:1053)
4       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1974)
5       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
6       at android.app.ActivityThread.access$600(ActivityThread.java:130)
7       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
8       at android.os.Handler.dispatchMessage(Handler.java:99)
9       at android.os.Looper.loop(Looper.java:137)
10      at android.app.ActivityThread.main(ActivityThread.java:4745)
11      at java.lang.reflect.Method.invokeNative(Native Method)
12      at java.lang.reflect.Method.invoke(Method.java:511)
13      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
14      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
15      at dalvik.system.NativeStart.main(Native Method)
16  Caused by: java.lang.UnsatisfiedLinkError: unknown failure
17      at java.lang.Runtime.loadLibrary(Runtime.java:370)
18      at java.lang.System.loadLibrary(System.java:535)
19      at com.dm.zbar.android.scanner.ZBarScannerActivity.<clinit>(ZBarScannerActivity.java:33)
20      ... 15 more
21  java.lang.UnsatisfiedLinkError: unknown failure
22      at java.lang.Runtime.loadLibrary(Runtime.java:370)
23      at java.lang.System.loadLibrary(System.java:535)
24      at com.dm.zbar.android.scanner.ZBarScannerActivity.<clinit>(ZBarScannerActivity.java:33)
25      at java.lang.Class.newInstanceImpl(Native Method)
26      at java.lang.Class.newInstance(Class.java:1319)
27      at android.app.Instrumentation.newActivity(Instrumentation.java:1053)
28      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1974)
29      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
30      at android.app.ActivityThread.access$600(ActivityThread.java:130)
31      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
32      at android.os.Handler.dispatchMessage(Handler.java:99)
33      at android.os.Looper.loop(Looper.java:137)
34      at android.app.ActivityThread.main(ActivityThread.java:4745)
35      at java.lang.reflect.Method.invokeNative(Native Method)
36      at java.lang.reflect.Method.invoke(Method.java:511)
37      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
38      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
39      at dalvik.system.NativeStart.main(Native Method)

**Comment by YakovAvramenko** [comment]
"app_version": "4.0.1", "system_version": "4.1.1"

**Comment by dm77** [comment]
Thank you for the bug report. I will no longer be maintaining this project. I will be spending my time on https://github.com/dm77/barcodescanner
