### ISSUE TITLE
Not working with device have Front camera only 

### ISSUE THREAD

**Issue by achinverma** [dm77/ZBarScanner#30]
Hi, i have used this lib with my Nexus 7 , and it has only front camera , and this Zbar lib doest not worked with the front camera, is there any code or something else which can help to work this lib with front camera ? otherwise it is working fine with my rest of device which have back camera

**Comment by dm77** [comment]
Hi @achinverma, thanks for the inquiry. The library currently doesn't support front-facing cameras. On top of that I don't think ZBar SDK supports front-facing cameras. But I do remember reading ZXing SDK has added support for front-facing cameras. 

Though I do own a Nexus 7 myself, I am inclined towards thinking that this is a corner-case. Sorry about that. But if this becomes important for a lot of people in the future then we can revisit. Thanks for understanding.
