### ISSUE TITLE
crashes if device has no back-facing cam (Nexus 7 for example)

### ISSUE THREAD

**Issue by tobiasheine** [dm77/ZBarScanner#7]
java.lang.NullPointerException
        at com.dm.zbar.android.scanner.CameraPreview.surfaceChanged(CameraPreview.java:154)

Camera.open returns null if there is no back-facing camera. Scanning does no more work if I open instead the front facing camera.

**Comment by dm77** [comment]
Good point.

 I would generally have the check for camera existence in the client app. For example look for a call to isCameraAvailable in the example: https://github.com/DushyanthMaguluru/ZBarScanner/blob/master/examples/ZBarScannerDemo/src/com/dm/zbar/android/examples/MainActivity.java

I guess I can update Scanner activity to return a result code which signifies an error when there is no camera.

I will also have to update the code to switch to the next available camera if the rear-facing camera isn't available. Thanks for bringing this to my attention.

**Comment by cesards** [comment]
Here the same
If you could resolve this, youw would make a very big favour... I uploaded my application to Google Play and 11 users are reporting this problem... it could report bad reviews...

Thank you in advance. I attach you all information I have provided by www.bugsense.com

By the way, I'm using the method : isCameraAvailable()

0java.lang.NullPointerException
1at com.dm.zbar.android.scanner.CameraPreview.surfaceChanged(CameraPreview.java:154)
2at android.view.SurfaceView.updateWindow(SurfaceView.java:587)
3at android.view.SurfaceView.access$000(SurfaceView.java:81)
4at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:169)
5at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:590)
6at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1799)
7at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2628)
8at android.os.Handler.dispatchMessage(Handler.java:99)
9at android.os.Looper.loop(Looper.java:137)
10at android.app.ActivityThread.main(ActivityThread.java:4511)
11at java.lang.reflect.Method.invokeNative(Native Method)
12at java.lang.reflect.Method.invoke(Method.java:511)
13at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
14at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
15at dalvik.system.NativeStart.main(Native Method)

1.0.0   ES  GT-I9100    4.0.4   N/A N/A 
1.0.0   ES  GT-I9100    2.3.3   N/A N/A 
1.0.0   ES  GT-S5830    2.3.4   N/A N/A 
1.1.0   ES  ST27i   4.0.4   N/A N/A 
1.1.0   ES  LG-P700 4.0.3   N/A N/A 
1.1.0   ES  GT-S5830i   2.3.6   N/A N/A 
1.1.0   ES  GT-I9100    4.0.4   N/A N/A 
1.1.0   ES  GT-I9100    4.0.3   N/A N/A 
1.1.0   ES  GT-I9100    4.0.4   N/A N/A 
1.1.0   ES  U8815N  2.3.6   N/A N/A

**Comment by cesards** [comment]
@DushyanthMaguluru are you gonna keep updating your library?

**Comment by dm77** [comment]
@m3n0R I intend to fix this issue. Apologies for the delay. I was under the assumption that using "isCameraAvailable" is a good way to prevent the crash. Will update today.

In the long-term, I haven't seen any updates for the zbar library for 11 months. So I probably won't add any new features until zbar is updated. 

If you are interested in using zxing instead, see this repo: https://github.com/DushyanthMaguluru/simple-zxing-integration

**Comment by dm77** [comment]
I just updated the ZBarScannerActivity to check and cancel request when either rear-facing camera is not available or when mCamera is null.

See commits:
https://github.com/DushyanthMaguluru/ZBarScanner/commit/f159520b786c52947d981371c04860cb556d250d
https://github.com/DushyanthMaguluru/ZBarScanner/commit/2e335fb706d9c3c312ed693eaa829a46591e7bc7

Please let me know if this resolves your issue. Thank you for your patience

**Comment by varunthakur** [comment]
i have integreted the zbar library for scanning in my app........when ever i open my scanning activity and lock the device(only in case of honeycomb, 4.0.0 and higher android devices/tabs....works fine for the gingerbread)......and unlock the device the area of the scanning freezes though we can even scan the barcode if it freezes but i have to go back and again launch the scanning activity in order to create the surface again.........

Please Help me with this because i have the sample application of zbar....it behave the same way....is there any issue with the library......what is the appropriate fix for this  ???????????.

**Comment by trietbui85** [comment]
Is this bug fixed? If so, please close it.

**Comment by varunthakur** [comment]
Its certainly not fixed on my end but if u have any solution or any guidelines to live upto then please provide me with some too..... :+1:

**Comment by dm77** [comment]
@varunthakur: As I understand, your issue is what you mentioned in #8. @anticafe is speaking about this particular problem mentioned above, which I believe is fixed.

**Comment by varunthakur** [comment]
@DushyanthMaguluru  : i am sorry for mismatching the context.
But are there any solutions to my issue #8 ...................???????????

**Comment by dm77** [comment]
Hi @varunthakur,

I was able to duplicate your problem on my android 4.2 device and I am
working on a fix. It will be ready in a few hours.

Thanks,
Dushyanth
