### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by semanticart** [dm77/ZBarScanner#9]
Thanks for a great project. Is there an easy way to use this in portrait mode? I tried making the obvious tweak in the manifest.

**Comment by dm77** [comment]
Please see my commit in the portrait branch. Meanwhile I will work on way to dynamically adapt to portrait/landscape modes based on the declaration in the manifest.

**Comment by semanticart** [comment]
Thanks for the prompt reply!

**Comment by dm77** [comment]
I will no longer be maintaining this project. I will be spending my time on https://github.com/dm77/barcodescanner which supports portrait mode out of the box.
